apiVersion: apps/v1
kind: Deployment
metadata:
  name: nn-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nn-backend
  template:
    metadata:
      labels:
        app: nn-backend
    spec:
      containers:
      - name: nn-backend
        image: test1repo.azurecr.io/nn_backend:$imageTag  # Replace with your image name
        #command: ["bash", "-c", "nvidia-smi && tail -f /dev/null"]
        ports:
        - containerPort: 8080
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            nvidia.com/gpu: 1 