apiVersion: v1
kind: Service
metadata:
  name: nn-backend-service
spec:
  selector:
    app: nn-backend
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
  type: ClusterIP  # Change to ClusterIP
