apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: test1repo.azurecr.io/react_app:101 # Replace with your image name
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"  # Adjust according to your application needs
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://nn-backend-service"  # Set the backend URL
        tty: true
        stdin: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
#kubectl port-forward service/react-app-service 8080:80