name: CUDA Build

on:
  workflow_dispatch:  # Manually trigger the workflow
#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      nn_backend:
        image: nvidia/cuda:12.3.2-devel-ubuntu22.04
        ports:
          - "8080:8080"
        options: --privileged  # Required for GPU access
        env:
          NVIDIA_VISIBLE_DEVICES: all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: test1repo.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and deploy nn_backend
        run: | 
          docker build ./NN_backend -t test1repo.azurecr.io/nn_backend:${GITHUB_RUN_NUMBER}
          docker push test1repo.azurecr.io/nn_backend:${GITHUB_RUN_NUMBER}

      - name: Build and deploy react_app
        run: |
          docker build ./react_app -t test1repo.azurecr.io/react_app:${GITHUB_RUN_NUMBER}
          docker push test1repo.azurecr.io/react_app:${GITHUB_RUN_NUMBER}
 
 
